### ISSUE TITLE
Por qué se excluye pfmovil.properties en el WAR plugin ?

### ISSUE THREAD

**Issue by erny** [ctt-gob-es/portafirmas-proxy#1]
Al crear el WAR se excluye este .properties. ¿Por qué? Las instrucciones de instalación indican que lo incluye en el WAR. Es commit a4a6b11 de Oct 2016 (Carlos)

**Comment by erny** [comment]
Por qué se excluye maven descriptor?

**Comment by agustinjm** [comment]
Buenos días necesito los war que funcionan para portafirmas v7.1, necesito war de los siguientes despliegues:

portafirmas-proxy
afirma-server-triphase-signer

Gracias.

**Comment by agustinjm** [comment]
Hola de nuevo, con la actual versión de portafirmas-proxy tengo el siguiente error al intentar conectar con la app, alguna idea?

14:25:05.290 [https-jsse-nio-4443-exec-6] WARN es.gob.afirma.signfolder.server.proxy.ProxyService - El Portafirmas devolvio un error
com.sun.xml.internal.ws.spi.db.DatabindingException: com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 13 counts of IllegalAnnotationExceptions
Property roles is present but not specified in @XmlType.propOrder
	this problem is related to the following location:
		at protected java.util.List es.gob.afirma.signfolder.client.MobileApplicationList.roles
		at es.gob.afirma.signfolder.client.MobileApplicationList
		at protected es.gob.afirma.signfolder.client.MobileApplicationList es.gob.afirma.signfolder.client.QueryApplicationsMobileResponse.applicationList
		at es.gob.afirma.signfolder.client.QueryApplicationsMobileResponse
		at public es.gob.afirma.signfolder.client.QueryApplicationsMobileResponse es.gob.afirma.signfolder.client.ObjectFactory.createQueryApplicationsMobileResponse()
		at es.gob.afirma.signfolder.client.ObjectFactory
Property role is present but not specified in @XmlType.propOrder
	this problem is related to the following location:
		at private java.lang.String es.gob.afirma.signfolder.client.GetUserByRoleRequest.role
		at es.gob.afirma.signfolder.client.GetUserByRoleRequest
Property id is present but not specified in @XmlType.propOrder
	this problem is related to the following location:
		at private byte[] es.gob.afirma.signfolder.client.GetUserByRoleRequest.id
		at es.gob.afirma.signfolder.client.GetUserByRoleRequest
Property role, id appears in @XmlType.propOrder, but no such property exists. Maybe you meant role?
	this problem is related to the following location:
		at es.gob.afirma.signfolder.client.GetUserByRoleRequest
Property id is present but not specified in @XmlType.propOrder
	this problem is related to the following location:
		at private byte[] es.gob.afirma.signfolder.client.VerifyPetitionsRequest.id
		at es.gob.afirma.signfolder.client.VerifyPetitionsRequest
Property petitions is present but not specified in @XmlType.propOrder
	this problem is related to the following location:
		at private java.util.List es.gob.afirma.signfolder.client.VerifyPetitionsRequest.petitions
		at es.gob.afirma.signfolder.client.VerifyPetitionsRequest
Property id, petitions appears in @XmlType.propOrder, but no such property exists. Maybe you meant petitions?
	this problem is related to the following location:
		at es.gob.afirma.signfolder.client.VerifyPetitionsRequest
Property id is present but not specified in @XmlType.propOrder
	this problem is related to the following location:
		at private byte[] es.gob.afirma.signfolder.client.CreateRoleRequest.id
		at es.gob.afirma.signfolder.client.CreateRoleRequest
Property userId is present but not specified in @XmlType.propOrder
	this problem is related to the following location:
		at private java.lang.String es.gob.afirma.signfolder.client.CreateRoleRequest.userId
		at es.gob.afirma.signfolder.client.CreateRoleRequest
Property selectedRole is present but not specified in @XmlType.propOrder
	this problem is related to the following location:
		at private java.lang.String es.gob.afirma.signfolder.client.CreateRoleRequest.selectedRole
		at es.gob.afirma.signfolder.client.CreateRoleRequest
Property authInfo is present but not specified in @XmlType.propOrder
	this problem is related to the following location:
		at private es.gob.afirma.signfolder.client.AuthorizationInfo es.gob.afirma.signfolder.client.CreateRoleRequest.authInfo
		at es.gob.afirma.signfolder.client.CreateRoleRequest
Property appIds is present but not specified in @XmlType.propOrder
	this problem is related to the following location:
		at private java.util.List es.gob.afirma.signfolder.client.CreateRoleRequest.appIds
		at es.gob.afirma.signfolder.client.CreateRoleRequest
Property id, userId, selectedRole, authInfo, appIds appears in @XmlType.propOrder, but no such property exists. Maybe you meant selectedRole?
	this problem is related to the following location:
		at es.gob.afirma.signfolder.client.CreateRoleRequest

	at com.sun.xml.internal.ws.db.glassfish.JAXBRIContextFactory.newContext(JAXBRIContextFactory.java:90)
	at com.sun.xml.internal.ws.spi.db.BindingContextFactory.create(BindingContextFactory.java:167)
	at com.sun.xml.internal.ws.model.AbstractSEIModelImpl$1.run(AbstractSEIModelImpl.java:203)
	at com.sun.xml.internal.ws.model.AbstractSEIModelImpl$1.run(AbstractSEIModelImpl.java:176)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.xml.internal.ws.model.AbstractSEIModelImpl.createJAXBContext(AbstractSEIModelImpl.java:176)
	at com.sun.xml.internal.ws.model.AbstractSEIModelImpl.postProcess(AbstractSEIModelImpl.java:95)
	at com.sun.xml.internal.ws.model.RuntimeModeler.buildRuntimeModel(RuntimeModeler.java:309)
	at com.sun.xml.internal.ws.db.DatabindingImpl.<init>(DatabindingImpl.java:85)
	at com.sun.xml.internal.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:59)
	at com.sun.xml.internal.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:43)
	at com.sun.xml.internal.ws.db.DatabindingFactoryImpl.createRuntime(DatabindingFactoryImpl.java:105)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.buildRuntimeModel(WSServiceDelegate.java:875)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.createSEIPortInfo(WSServiceDelegate.java:892)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.addSEI(WSServiceDelegate.java:855)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:435)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:404)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:386)
	at javax.xml.ws.Service.getPort(Service.java:119)
	at es.gob.afirma.signfolder.client.MobileService_Service.getMobileServicePort(MobileService_Service.java:73)
	at es.gob.afirma.signfolder.server.proxy.ProxyService.getService(ProxyService.java:2173)
	at es.gob.afirma.signfolder.server.proxy.ProxyService.processRequestClaveLogin(ProxyService.java:728)
	at es.gob.afirma.signfolder.server.proxy.ProxyService.processRequest(ProxyService.java:389)
	at es.gob.afirma.signfolder.server.proxy.ProxyService.service(ProxyService.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 13 counts of IllegalAnnotationExceptions
	at com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:91)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:445)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:277)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:124)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1123)
	at com.sun.xml.internal.bind.v2.ContextFactory.createContext(ContextFactory.java:147)
	at com.sun.xml.internal.bind.api.JAXBRIContext.newInstance(JAXBRIContext.java:152)
	at com.sun.xml.internal.bind.api.JAXBRIContext.newInstance(JAXBRIContext.java:96)
	at com.sun.xml.internal.ws.developer.JAXBContextFactory$1.createJAXBContext(JAXBContextFactory.java:98)
	at com.sun.xml.internal.ws.db.glassfish.JAXBRIContextFactory.newContext(JAXBRIContextFactory.java:79)
	... 46 common frames omitted
14:25:05.291 [https-jsse-nio-4443-exec-6] DEBUG es.gob.afirma.signfolder.server.proxy.ProxyService - XML de respuesta:
<err cd="ERR-10">Error desconocido en las peticiones al portafirmas</err>
14:25:05.291 [https-jsse-nio-4443-exec-6] DEBUG es.gob.afirma.signfolder.server.proxy.ProxyService - Fin peticion ProxyService

Saludos.

**Comment by CGamuci-RES-DBS-APL** [comment]
Hola Agustín,

La versión que hay actualmente en SNAPSHOT del servicio proxy incluye mejoras y nuevas funcionalidades que no se soportan en la versión de la app que hay publicada en las tiendas. El error concreto, es que la versión publicada de la aplicación móvil aún no soporta roles de usuario, que es una de las funcionalidades nuevas del proxy, que tampoco está soportada en la última versión del Portafirmas web (v7.1). Cada versión de Portafirmas web debe utilizar una versión concreta del servicio proxy. Consulta con los responsables del Portafirmas web cuál corresponde con vuestra distribución.

Con el modelo actual de las tiendas de aplicaciones móviles, es muy fácil para los usuarios el actualizar a la última versión de las aplicaciones o que se les actualicen automáticamente, incluso. Sin embargo, ya es más difícil que quienes tengan desplegada una versión del Portafirmas web actualicen el servicio proxy. Es por eso que en este proyecto tenemos cuidado de que la última versión de las aplicaciones móviles sea compatible con versiones de proxy antiguas (las de los Portafirmas web ya desplegados), pero los proxies nuevos no siempre son compatibles con versiones antiguas de la app.

Un saludo.

**Comment by CGamuci-RES-DBS-APL** [comment]
Hola @erny,

El servicio proxy permite que se le pase la propiedad "pfmovil.config.path" con la que se puede configurar el directorio del servidor con en el que se encuentra el fichero "pfmovil.properties". Esto puede hacerse, por ejemplo, pasándole al servidor de aplicaciones el parámetro "-Dpfmovil.config.path=RUTA_DIRECTORIO" durante el arranque, donde RUTA DIRECTORIO sería la ruta del directorio en el que se encuentra "pfmovil.properties".

El fichero properties debería estar fuera del WAR. Así se podría cambiar la configuración del servicio sin necesidad de abrir y modificar el archivo. Si no se encuentra establecida la propiedad, el fichero se seguirá buscando dentro del WAR como ya hacía antes.

Un saludo,

**Comment by agustinjm** [comment]
> Hola Agustín,
> 
> La versión que hay actualmente en SNAPSHOT del servicio proxy incluye mejoras y nuevas funcionalidades que no se soportan en la versión de la app que hay publicada en las tiendas. El error concreto, es que la versión publicada de la aplicación móvil aún no soporta roles de usuario, que es una de las funcionalidades nuevas del proxy, que tampoco está soportada en la última versión del Portafirmas web (v7.1). Cada versión de Portafirmas web debe utilizar una versión concreta del servicio proxy. Consulta con los responsables del Portafirmas web cuál corresponde con vuestra distribución.
> 
> Con el modelo actual de las tiendas de aplicaciones móviles, es muy fácil para los usuarios el actualizar a la última versión de las aplicaciones o que se les actualicen automáticamente, incluso. Sin embargo, ya es más difícil que quienes tengan desplegada una versión del Portafirmas web actualicen el servicio proxy. Es por eso que en este proyecto tenemos cuidado de que la última versión de las aplicaciones móviles sea compatible con versiones de proxy antiguas (las de los Portafirmas web ya desplegados), pero los proxies nuevos no siempre son compatibles con versiones antiguas de la app.
> 
> Un saludo.

Hola Carlos, **ya me funciona la app!** estoy probando pero tiene buena pinta, gracias por tu ayuda,

Pues estudiando el código he ido comentando o dejando nulas las llamadas a los métodos del servicio MobileService que están actualmente implementados en la última versión del portafirmas y que yo no están en versión 7.1.

También he tenido un problema con identificación por Cl@ve en la aplicación móvil, la llamada busca la jsp clave-loading.jsp en una en el contexto **nombre_del_war/pf/clave-loading.jsp**

Una vez que veía en la trazas que había terminado ProxyService y que ya había creado sesión para entrar el servidor Tomcat me daba cantidad de problemas de este tipo:

SEVERE [https-jsse-nio2-4443-exec-9] org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun Error running socket processor
	java.lang.NullPointerException
		at org.bouncycastle.crypto.signers.PSSSigner.generateSignature(Unknown Source)
		at org.bouncycastle.jcajce.provider.asymmetric.rsa.PSSSignatureSpi.engineSign(Unknown Source)
		at java.security.Signature$Delegate.engineSign(Signature.java:1382)
		at java.security.Signature.sign(Signature.java:698)
		at sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeMessage.<init>(ECDHServerKeyExchange.java:177)

Lo he solucionado tocando la configuración del conector del **server.xml** y añadiendo al móvil la **clave pública raíz de la entidad de certificación de mi certificado de dominio**.

Dicho esto ya me está funcionando la app en Android 10, y he de decir que me da muy buena impresión, va fluida, también he conseguido firmar.

Saludos!

**Comment by CGamuci-RES-DBS-APL** [comment]
Me alegro de que te funcione.

Para el uso de Cl@ve se deben cargar las páginas de Cl@ve y alguna página intermedia a través de la que le hacemos el envío de datos. Estas páginas se cargan en un WebView en la aplicación que no es más que un navegador al que, si no le gusta el certificado SSL del dominio, va a rechazar la conexión. Si despliegas el servicios sobre un dominio con un certificado SSL reconocido nativamente por el sistema operativo, no deberías tener problema.

Un saludo.
